import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { 
  Search, 
  Filter, 
  ArrowUpDown, 
  AlertOctagon, 
  ChevronRight, 
  Eye, 
  FolderPlus,
  RefreshCw,
  Clock,
  Coins
} from 'lucide-react';
import { api } from '../services/api';
import { formatINR, formatDate, getRiskBadgeClass } from '../utils/formatters';
import RiskScoreBadge from '../components/RiskScoreBadge';
import EmptyState from '../components/EmptyState';

export default function RiskQueue() {
  const [items, setItems] = useState([]);
  const [districts, setDistricts] = useState([]);
  const [categories, setCategories] = useState([]);
  const [loading, setLoading] = useState(true);

  // Filters
  const [riskLevel, setRiskLevel] = useState('');
  const [district, setDistrict] = useState('');
  const [category, setCategory] = useState('');
  const [status, setStatus] = useState('');
  const [search, setSearch] = useState('');
  const [sortBy, setSortBy] = useState('score');
  const [sortDir, setSortDir] = useState('desc');

  // Pagination
  const [page, setPage] = useState(0);
  const [totalPages, setTotalPages] = useState(1);
  const [totalElements, setTotalElements] = useState(0);

  const loadFilters = async () => {
    try {
      const [dList, cList] = await Promise.all([
        api.getDistricts(),
        api.getCategories()
      ]);
      setDistricts(dList || []);
      setCategories(cList || []);
    } catch (e) {
      console.error(e);
    }
  };

  const loadQueue = async () => {
    setLoading(true);
    try {
      const res = await api.getRiskQueue({
        riskLevel,
        district,
        category,
        status,
        search,
        sortBy,
        sortDir,
        page,
        size: 20
      });
      if (res) {
        setItems(res.content || []);
        setTotalPages(res.totalPages || 1);
        setTotalElements(res.totalElements || 0);
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadFilters();
  }, []);

  useEffect(() => {
    loadQueue();
  }, [riskLevel, district, category, status, sortBy, sortDir, page]);

  const handleSearchSubmit = (e) => {
    e.preventDefault();
    setPage(0);
    loadQueue();
  };

  return (
    <div className="p-6 space-y-6 max-w-7xl mx-auto">
      
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-xl font-black tracking-tight text-slate-900">PRIORITIZED RISK QUEUE</h1>
            <span className="px-2.5 py-0.5 rounded-full text-xs font-mono font-bold bg-red-100 text-red-800 border border-red-200">
              {totalElements} Works
            </span>
          </div>
          <p className="text-xs text-slate-500 mt-1">
            Prioritized investigation queue generated by explainable multi-signal anomaly detection.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={() => { setPage(0); loadQueue(); }}
            className="p-2 rounded-lg bg-white border border-slate-200 text-slate-600 hover:bg-slate-50 text-xs font-medium shadow-xs transition flex items-center gap-1.5"
            title="Refresh list"
          >
            <RefreshCw className="w-3.5 h-3.5" />
            <span>Refresh</span>
          </button>
        </div>
      </div>

      {/* Filter Toolbar */}
      <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-xs space-y-3">
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-5 gap-3 text-xs">
          
          {/* Risk Level Filter */}
          <div>
            <label className="block font-semibold text-slate-600 mb-1">Risk Level</label>
            <select
              value={riskLevel}
              onChange={(e) => { setRiskLevel(e.target.value); setPage(0); }}
              className="w-full bg-slate-50 border border-slate-200 rounded-lg p-2 font-medium text-slate-800 focus:outline-none focus:border-blue-500"
            >
              <option value="">All Risk Levels</option>
              <option value="HIGH">🔴 High Risk (70–100)</option>
              <option value="MEDIUM">🟡 Medium Risk (40–69)</option>
              <option value="LOW">🟢 Low Risk (0–39)</option>
            </select>
          </div>

          {/* District Filter */}
          <div>
            <label className="block font-semibold text-slate-600 mb-1">District</label>
            <select
              value={district}
              onChange={(e) => { setDistrict(e.target.value); setPage(0); }}
              className="w-full bg-slate-50 border border-slate-200 rounded-lg p-2 font-medium text-slate-800 focus:outline-none focus:border-blue-500"
            >
              <option value="">All Districts</option>
              {districts.map((d, i) => (
                <option key={i} value={d}>{d}</option>
              ))}
            </select>
          </div>

          {/* Category Filter */}
          <div>
            <label className="block font-semibold text-slate-600 mb-1">Work Sector / Category</label>
            <select
              value={category}
              onChange={(e) => { setCategory(e.target.value); setPage(0); }}
              className="w-full bg-slate-50 border border-slate-200 rounded-lg p-2 font-medium text-slate-800 focus:outline-none focus:border-blue-500"
            >
              <option value="">All Categories</option>
              {categories.map((c, i) => (
                <option key={i} value={c}>{c}</option>
              ))}
            </select>
          </div>

          {/* Status Filter */}
          <div>
            <label className="block font-semibold text-slate-600 mb-1">Execution Status</label>
            <select
              value={status}
              onChange={(e) => { setStatus(e.target.value); setPage(0); }}
              className="w-full bg-slate-50 border border-slate-200 rounded-lg p-2 font-medium text-slate-800 focus:outline-none focus:border-blue-500"
            >
              <option value="">All Statuses</option>
              <option value="Ongoing">Ongoing</option>
              <option value="Completed">Completed</option>
              <option value="Sanctioned">Sanctioned</option>
            </select>
          </div>

          {/* Sort Option */}
          <div>
            <label className="block font-semibold text-slate-600 mb-1">Sort Ranking</label>
            <select
              value={`${sortBy}_${sortDir}`}
              onChange={(e) => {
                const [sb, sd] = e.target.value.split('_');
                setSortBy(sb);
                setSortDir(sd);
                setPage(0);
              }}
              className="w-full bg-slate-50 border border-slate-200 rounded-lg p-2 font-medium text-slate-800 focus:outline-none focus:border-blue-500"
            >
              <option value="score_desc">Highest Risk Score</option>
              <option value="score_asc">Lowest Risk Score</option>
              <option value="cost_desc">Highest Cost</option>
              <option value="delay_desc">Longest Delay</option>
            </select>
          </div>

        </div>

        {/* Live Search Bar */}
        <form onSubmit={handleSearchSubmit} className="pt-2 border-t border-slate-100 flex items-center gap-2">
          <div className="relative flex-1">
            <Search className="w-4 h-4 text-slate-400 absolute left-3 top-2.5" />
            <input
              type="text"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="Search by Work ID, Project Title, Village or Implementing Agency..."
              className="w-full bg-slate-50 border border-slate-200 rounded-lg pl-9 pr-3 py-2 text-xs text-slate-800 focus:outline-none focus:border-blue-500 placeholder-slate-400"
            />
          </div>
          <button
            type="submit"
            className="px-4 py-2 bg-gov-navy hover:bg-gov-dark text-white rounded-lg text-xs font-semibold shadow-xs transition"
          >
            Search
          </button>
        </form>
      </div>

      {/* Queue Table */}
      <div className="bg-white rounded-xl border border-slate-200 shadow-xs overflow-hidden">
        {loading ? (
          <div className="p-12 text-center text-xs text-slate-500">
            <div className="w-8 h-8 border-3 border-blue-600 border-t-transparent rounded-full animate-spin mx-auto mb-2" />
            Filtering risk queue...
          </div>
        ) : items.length === 0 ? (
          <div className="p-8">
            <EmptyState
              title="No works matching the selected criteria"
              message="Adjust your filters or search keywords to view other MPLADS works."
              actionText="Reset All Filters"
              onActionClick={() => {
                setRiskLevel('');
                setDistrict('');
                setCategory('');
                setStatus('');
                setSearch('');
                setPage(0);
              }}
            />
          </div>
        ) : (
          <>
            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs">
                <thead className="bg-slate-50 border-b border-slate-200 text-slate-600 font-bold uppercase tracking-wider">
                  <tr>
                    <th className="py-3 px-4">Priority / Score</th>
                    <th className="py-3 px-4">Work ID</th>
                    <th className="py-3 px-4">Project Title &amp; Location</th>
                    <th className="py-3 px-4">Category</th>
                    <th className="py-3 px-4">Sanctioned Cost</th>
                    <th className="py-3 px-4">Delay Days</th>
                    <th className="py-3 px-4">Primary Anomaly Signal</th>
                    <th className="py-3 px-4">Inquiry Status</th>
                    <th className="py-3 px-4 text-right">Dossier</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 font-medium">
                  {items.map((item, idx) => (
                    <tr key={idx} className="hover:bg-slate-50 transition group">
                      
                      {/* Priority / Score */}
                      <td className="py-3.5 px-4 whitespace-nowrap">
                        <RiskScoreBadge score={item.riskScore} level={item.riskLevel} />
                      </td>

                      {/* Work ID */}
                      <td className="py-3.5 px-4 font-mono font-bold text-slate-900 whitespace-nowrap">
                        <Link to={`/passport/${item.workId}`} className="hover:text-blue-600 underline-offset-2 hover:underline">
                          {item.workId}
                        </Link>
                      </td>

                      {/* Title & Location */}
                      <td className="py-3.5 px-4 max-w-xs">
                        <Link to={`/passport/${item.workId}`} className="font-semibold text-slate-900 hover:text-blue-600 block line-clamp-1">
                          {item.workName}
                        </Link>
                        <span className="text-[11px] text-slate-400 block mt-0.5">
                          {item.district}, {item.state}
                        </span>
                      </td>

                      {/* Category */}
                      <td className="py-3.5 px-4 text-slate-700 whitespace-nowrap">
                        <span className="px-2 py-0.5 rounded bg-slate-100 text-slate-700 text-[11px] font-medium">
                          {item.category}
                        </span>
                      </td>

                      {/* Cost */}
                      <td className="py-3.5 px-4 font-mono font-bold text-slate-900 whitespace-nowrap">
                        {formatINR(item.sanctionedAmount)}
                      </td>

                      {/* Delay */}
                      <td className="py-3.5 px-4 font-mono whitespace-nowrap">
                        {item.delayDays > 30 ? (
                          <span className="text-amber-700 font-semibold flex items-center gap-1">
                            <Clock className="w-3 h-3 text-amber-500" />
                            +{item.delayDays}d
                          </span>
                        ) : (
                          <span className="text-emerald-700">0d</span>
                        )}
                      </td>

                      {/* Primary Signal */}
                      <td className="py-3.5 px-4 max-w-xs truncate text-[11px] text-slate-600" title={item.primaryReason}>
                        {item.primaryReason}
                      </td>

                      {/* Inquiry status */}
                      <td className="py-3.5 px-4 whitespace-nowrap">
                        {item.hasOpenInvestigation ? (
                          <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-blue-100 text-blue-800 border border-blue-200">
                            {item.investigationStatus || 'UNDER REVIEW'}
                          </span>
                        ) : (
                          <span className="text-slate-400 text-[11px]">—</span>
                        )}
                      </td>

                      {/* Action */}
                      <td className="py-3.5 px-4 text-right whitespace-nowrap">
                        <Link
                          to={`/passport/${item.workId}`}
                          className="inline-flex items-center gap-1 px-2.5 py-1 rounded bg-gov-navy text-white hover:bg-gov-dark font-semibold text-[11px] transition shadow-xs"
                        >
                          <Eye className="w-3.5 h-3.5" />
                          <span>Inspect</span>
                        </Link>
                      </td>

                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* Pagination footer */}
            <div className="p-4 border-t border-slate-200 flex items-center justify-between text-xs text-slate-600 bg-slate-50">
              <div>
                Showing page <span className="font-bold">{page + 1}</span> of <span className="font-bold">{totalPages}</span> ({totalElements} total works)
              </div>
              <div className="flex items-center gap-2">
                <button
                  onClick={() => setPage(Math.max(0, page - 1))}
                  disabled={page === 0}
                  className="px-3 py-1 bg-white border border-slate-200 rounded text-slate-700 font-semibold disabled:opacity-40 hover:bg-slate-100 transition"
                >
                  Previous
                </button>
                <button
                  onClick={() => setPage(Math.min(totalPages - 1, page + 1))}
                  disabled={page >= totalPages - 1}
                  className="px-3 py-1 bg-white border border-slate-200 rounded text-slate-700 font-semibold disabled:opacity-40 hover:bg-slate-100 transition"
                >
                  Next
                </button>
              </div>
            </div>
          </>
        )}
      </div>

    </div>
  );
}
